name: Wasm Deploy
on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: Swatinem/rust-cache@v2
      
      
      - name: Set default toolchain to nightly
        run: rustup default nightly
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - uses: jetli/trunk-action@v0.1.0

      - uses: actions/checkout@v2

      - run: trunk build --release --public-url /pomotime/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          # Path of the directory containing the static assets.
          path: ./dist

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.4
